//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94.355264
        ///94.347879
        ///93.665565
        ///94.259409
        ///94.542535
        ///94.449688
        ///95.174574
        ///95.012400
        ///95.600177
        ///95.534224
        ///95.433425
        ///95.427137
        ///95.489258
        ///96.216913
        ///96.857378
        ///97.016301
        ///96.890699
        ///96.642770
        ///96.901613
        ///97.322562
        ///96.636384
        ///96.995238
        ///96.774356
        ///97.412403
        ///97.802697
        ///97.522854
        ///97.538057
        ///97.230873
        ///97.207220
        ///97.372396
        ///97.350714
        ///97.734727
        ///97.685902
        ///97.351115
        ///97.072048
        ///97.164121
        ///97.061206
        ///97.092206
        ///96.752262
        ///96.901230
        ///96.853846
        ///96.798995
        ///96.757213
        ///96.731446
        ///96.800667
        ///96.802416
        ///96.966518
        ///97.116359
        ///97.495217
        ///97.645217
        ///97.915667
        ///97 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prix1 {
            get {
                return ResourceManager.GetString("Prix1", resourceCulture);
            }
        }
    }
}
