//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHF
        ///2014-02-28 0.02
        ///2014-01-31 0.02
        ///2013-12-31 0.02
        ///2013-11-30 0.02
        ///2013-10-31 0.02
        ///2013-09-30 0.02
        ///2013-08-31 0.02
        ///2013-07-31 0.02
        ///2013-06-30 0.02
        ///2013-05-31 0.02
        ///2013-04-30 0.02
        ///2013-03-31 0.02
        ///2013-02-28 0.01
        ///2013-01-31 0.02
        ///2012-12-31 0.01
        ///2012-11-30 0.03
        ///2012-10-31 0.04
        ///2012-09-30 0.05
        ///2012-08-31 0.05
        ///2012-07-31 0.07
        ///2012-06-30 0.09
        ///2012-05-31 0.11
        ///2012-04-30 0.11
        ///2012-03-31 0.1
        ///2012-02-29 0.08
        ///2012-01-31 0.06
        ///2011-12-31 0.05
        ///2011-11-30 0.05
        ///2011-10-31 0.04
        ///2011-09-30 0.01 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chfRate {
            get {
                return ResourceManager.GetString("chfRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBDRY ENLAY HSEA DEO TSCDF WFC PEP NVS GBPEUR USDEUR CHFEUR 
        ///0.103575 0.103889 0.103927 0.103100 0.102850 
        ///0.118168 0.111034 0.086754 0.086195 0.117317 
        ///0.124616 0.125548 0.085588 0.081024 0.119197 
        ///0.120752 0.135806 0.078316 0.086935 0.101547 
        ///0.141479 0.129659 0.066877 0.076109 0.106512 
        ///0.143866 0.142688 0.075803 0.076381 0.082808 
        ///0.131899 0.142665 0.074376 0.073490 0.084662 
        ///0.144953 0.148292 0.067018 0.063710 0.091512 
        ///0.134245 0.130640 0.076640 0.058762 0.101239 
        ///0.150716 0.133292 0.067057  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deltas1 {
            get {
                return ResourceManager.GetString("Deltas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBDRY ENLAY HSEA DEO TSCDF WFC PEP NVS GBPEUR USDEUR CHFEUR 
        ///0.111701 0.112742 0.111578 0.111390 0.112358 
        ///0.135294 0.098703 0.110545 0.122943 0.103426 
        ///0.138587 0.112021 0.106155 0.112148 0.098333 
        ///0.139337 0.099085 0.128768 0.086019 0.119196 
        ///0.142718 0.107216 0.091169 0.100019 0.130495 
        ///0.147706 0.094195 0.097858 0.119205 0.130316 
        ///0.139253 0.074437 0.096559 0.143926 0.138419 
        ///0.122840 0.072204 0.104933 0.144430 0.137007 
        ///0.155716 0.066609 0.080096 0.141259 0.155540 
        ///0.145838 0.072093 0.074263  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deltas2 {
            get {
                return ResourceManager.GetString("Deltas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  IBDRY ENLAY HSEA DEO TSCDF WFC PEP NVS GBPEUR USDEUR CHFEUR 
        ///0.123999 0.124560 0.123048 0.124449 0.123805 
        ///0.138807 0.139454 0.128684 0.137688 0.083931 
        ///0.121202 0.140247 0.113702 0.159550 0.092368 
        ///0.109026 0.131601 0.132036 0.169451 0.084580 
        ///0.096191 0.136553 0.127900 0.200053 0.066133 
        ///0.093298 0.143214 0.127912 0.194168 0.069019 
        ///0.100673 0.124589 0.141578 0.170118 0.071227 
        ///0.091974 0.132170 0.135522 0.187170 0.070364 
        ///0.091570 0.131484 0.127552 0.179209 0.078200 
        ///0.077261 0.136752 0.119413 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deltas3 {
            get {
                return ResourceManager.GetString("Deltas3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR
        ///08/31/2005 2.112
        ///09/01/2005 2.112
        ///09/02/2005 2.112
        ///09/05/2005 2.112
        ///09/06/2005 2.113
        ///09/07/2005 2.114
        ///09/08/2005 2.114
        ///09/09/2005 2.114
        ///09/12/2005 2.113
        ///09/13/2005 2.115
        ///09/14/2005 2.114
        ///09/15/2005 2.115
        ///09/16/2005 2.115
        ///09/19/2005 2.114
        ///09/20/2005 2.114
        ///09/21/2005 2.114
        ///09/22/2005 2.114
        ///09/23/2005 2.114
        ///09/26/2005 2.117
        ///09/27/2005 2.119
        ///09/28/2005 2.122
        ///09/29/2005 2.121
        ///09/30/2005 2.122
        ///10/03/2005 2.122
        ///10/04/2005 2.121
        ///10/05/2005 2.123
        ///10/06/2005 2.123
        ///10/07/2005 2.124
        ///10/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eurRate {
            get {
                return ResourceManager.GetString("eurRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP
        ///2005-08-31 4.59063
        ///2005-09-01 4.59063
        ///2005-09-02 4.59250
        ///2005-09-05 4.58625
        ///2005-09-06 4.59000
        ///2005-09-07 4.59000
        ///2005-09-08 4.59000
        ///2005-09-09 4.59125
        ///2005-09-12 4.59438
        ///2005-09-13 4.59250
        ///2005-09-14 4.60125
        ///2005-09-15 4.60406
        ///2005-09-16 4.60125
        ///2005-09-19 4.59875
        ///2005-09-20 4.59813
        ///2005-09-21 4.59813
        ///2005-09-22 4.59250
        ///2005-09-23 4.59313
        ///2005-09-26 4.60563
        ///2005-09-27 4.61250
        ///2005-09-28 4.61375
        ///2005-09-29 4.61188
        ///2005-09-30 4.60125
        ///2005-10-03 4.60250
        ///2005-10-04 4.59625
        ///2005-10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gbpRate {
            get {
                return ResourceManager.GetString("gbpRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBDRY ENLAY HSEA DEO TSCDF WFC PEP NVS GBPEUR USDEUR CHFEUR 
        ///100.000000 100.000000 100.000000 100.000000 100.000000 
        ///97.971588 99.059206 102.269219 102.545536 98.124214 
        ///96.274922 96.117635 101.274791 101.927842 96.923634 
        ///97.394924 95.731815 103.172259 101.899384 99.836771 
        ///95.661483 96.863988 105.896536 104.158328 99.661501 
        ///95.091692 95.223413 103.829025 103.884486 102.767859 
        ///97.234947 95.996418 105.234639 105.592241 103.433666 
        ///95.747680 95.303107 106.555877 107.200109 102.189493 
        ///97.313333 97 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Market1 {
            get {
                return ResourceManager.GetString("Market1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBDRY ENLAY HSEA DEO TSCDF WFC PEP NVS GBPEUR USDEUR CHFEUR 
        ///100.000000 100.000000 100.000000 100.000000 100.000000 
        ///97.299172 105.986478 103.124608 100.221702 105.042858 
        ///95.356552 101.061236 102.624213 101.086022 104.798361 
        ///95.669927 104.707219 97.573762 108.423598 99.715996 
        ///94.798315 102.566101 107.020736 104.516074 97.464093 
        ///99.397688 112.034191 111.351757 105.498959 102.809215 
        ///99.894634 117.661291 110.298357 99.173912 100.269624 
        ///101.007856 114.426479 105.001120 96.319307 97.928394 
        ///97.112 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Market2 {
            get {
                return ResourceManager.GetString("Market2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBDRY ENLAY HSEA DEO TSCDF WFC PEP NVS DTE.DE GPDNF BP RBS PG JNJ GE C VZ NTT EOAN.DE OR.PA GBPEUR USDEUR CHFEUR EURJPY 
        ///30-1-2015 27.73 4.485 26.685 118.64 3.4 52.335 94.445 97.955 15.4 67.22 38.745 10.92 84.735 101.045 23.965 47.315 46.035 29.63 13.825 158.45 1.38252 0.926946 0.945802 129.725 
        ///29-1-2015 27.955 4.53 26.65 121.57 3.425 52.4 95.675 98.57 15.27 67.22 38.525 11.13 85.63 101.565 23.99 47.305 45.825 29.38 13.82 158.05 1.38541 0.936665 0.941478 129.146 
        ///28-1-2015 27.7 4.46 26.67 118.545 3.42 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Market3 {
            get {
                return ResourceManager.GetString("Market3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94.355264
        ///94.347879
        ///93.665565
        ///94.259409
        ///94.542535
        ///94.449688
        ///95.174574
        ///95.012400
        ///95.600177
        ///95.534224
        ///95.433425
        ///95.427137
        ///95.489258
        ///96.216913
        ///96.857378
        ///97.016301
        ///96.890699
        ///96.642770
        ///96.901613
        ///97.322562
        ///96.636384
        ///96.995238
        ///96.774356
        ///97.412403
        ///97.802697
        ///97.522854
        ///97.538057
        ///97.230873
        ///97.207220
        ///97.372396
        ///97.350714
        ///97.734727
        ///97.685902
        ///97.351115
        ///97.072048
        ///97.164121
        ///97.061206
        ///97.092206
        ///96.752262
        ///96.901230
        ///96.853846
        ///96.798995
        ///96.757213
        ///96.731446
        ///96.800667
        ///96.802416
        ///96.966 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prix1 {
            get {
                return ResourceManager.GetString("Prix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 93.308296
        ///94.608080
        ///94.069050
        ///94.170465
        ///94.379157
        ///97.282347
        ///96.705841
        ///95.493694
        ///96.720352
        ///96.051293
        ///96.254377
        ///97.898257
        ///97.981432
        ///97.271451
        ///96.542569
        ///95.530035
        ///95.821342
        ///96.294315
        ///95.074085
        ///95.152329
        ///94.304726
        ///95.544245
        ///95.696850
        ///95.112580
        ///94.894111
        ///96.006517
        ///96.069707
        ///96.450016
        ///97.248172
        ///97.492087
        ///97.451265
        ///96.408870
        ///96.521360
        ///96.995253
        ///96.205825
        ///95.888019
        ///95.963718
        ///95.657957
        ///95.087882
        ///94.985208
        ///95.075505
        ///94.935011
        ///94.915334
        ///95.555711
        ///95.398963
        ///95.196752
        ///95.351 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prix2 {
            get {
                return ResourceManager.GetString("Prix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97.713314
        ///96.705335
        ///96.916877
        ///96.965079
        ///97.729565
        ///97.605357
        ///99.537539
        ///98.411242
        ///99.262102
        ///98.832546
        ///99.753547
        ///99.114025
        ///97.261073
        ///96.860335
        ///96.333217
        ///95.789251
        ///95.710636
        ///95.861899
        ///95.053031
        ///95.294820
        ///96.324463
        ///95.745453
        ///97.206117
        ///96.970301
        ///97.211726
        ///96.289394
        ///96.363116
        ///96.699552
        ///97.518664
        ///97.686287
        ///97.689861
        ///98.252243
        ///97.813110
        ///97.822843
        ///97.634761
        ///98.512928
        ///97.450941
        ///97.076366
        ///97.097921
        ///96.965513
        ///97.279840
        ///98.363076
        ///96.997370
        ///96.775874
        ///96.221938
        ///96.080359
        ///95.699 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prix3 {
            get {
                return ResourceManager.GetString("Prix3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR GBP USD CHF YEN
        ///2015-01-30 0,17125 0,50256 0,17125 2,41 0,07286
        ///2015-01-29 0,1709 0,50381 0,1709 2,41 0,07571
        ///2015-01-28 0,1705 0,50444 0,1705 2,41 0,07143
        ///2015-01-27 0,168 0,50131 0,168 2,41 0,07286
        ///2015-01-26 0,169 0,50444 0,169 2,41 0,075
        ///2015-01-23 0,16775 0,50163 0,16775 2,41 0,07214
        ///2015-01-22 0,16825 0,50163 0,16825 2,41 0,07643
        ///2015-01-21 0,16675 0,50163 0,16675 2,41 0,07357
        ///2015-01-20 0,1685 0,50381 0,1685 2,41 0,07571
        ///2015-01-19 0,16875 0,50381 0,16875 2,41 0,07143
        ///2015-01-16 0,168  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD
        ///2005-08-31 3.71625
        ///2005-09-01 3.71625
        ///2005-09-02 3.68000
        ///2005-09-05 3.68938
        ///2005-09-06 3.70250
        ///2005-09-07 3.70438
        ///2005-09-08 3.72813
        ///2005-09-09 3.74000
        ///2005-09-12 3.75000
        ///2005-09-13 3.76813
        ///2005-09-14 3.77188
        ///2005-09-15 3.78938
        ///2005-09-16 3.79625
        ///2005-09-19 3.81188
        ///2005-09-20 3.81875
        ///2005-09-21 3.83000
        ///2005-09-22 3.83000
        ///2005-09-23 3.83000
        ///2005-09-26 3.83750
        ///2005-09-27 3.84000
        ///2005-09-28 3.84063
        ///2005-09-29 3.86000
        ///2005-09-30 3.86375
        ///2005-10-03 3.88000
        ///2005-10-04 3.89000
        ///2005-10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string usdRate {
            get {
                return ResourceManager.GetString("usdRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEN
        ///2005-08-31 0.04375
        ///2005-09-01 0.04375
        ///2005-09-02 0.04375
        ///2005-09-05 0.04438
        ///2005-09-06 0.04438
        ///2005-09-07 0.04438
        ///2005-09-08 0.04438
        ///2005-09-09 0.04438
        ///2005-09-12 0.04438
        ///2005-09-13 0.04375
        ///2005-09-14 0.04375
        ///2005-09-15 0.04438
        ///2005-09-16 0.04438
        ///2005-09-19 0.04375
        ///2005-09-20 0.04438
        ///2005-09-21 0.04438
        ///2005-09-22 0.04500
        ///2005-09-23 0.04500
        ///2005-09-26 0.04500
        ///2005-09-27 0.04688
        ///2005-09-28 0.04750
        ///2005-09-29 0.04625
        ///2005-09-30 0.04625
        ///2005-10-03 0.04750
        ///2005-10-04 0.04625
        ///2005-10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yenRate {
            get {
                return ResourceManager.GetString("yenRate", resourceCulture);
            }
        }
    }
}
