//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.103575 0.103889 0.103927 0.103100 0.102850 
        ///0.118168 0.111034 0.086754 0.086195 0.117317 
        ///0.124616 0.125548 0.085588 0.081024 0.119197 
        ///0.120752 0.135806 0.078316 0.086935 0.101547 
        ///0.141479 0.129659 0.066877 0.076109 0.106512 
        ///0.143866 0.142688 0.075803 0.076381 0.082808 
        ///0.131899 0.142665 0.074376 0.073490 0.084662 
        ///0.144953 0.148292 0.067018 0.063710 0.091512 
        ///0.134245 0.130640 0.076640 0.058762 0.101239 
        ///0.150716 0.133292 0.067057 0.059043 0.095394 
        ///0.166961 0.114222 0.065713 0.049857 0.116259 
        ///0.1696 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deltas1 {
            get {
                return ResourceManager.GetString("Deltas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.111701 0.112742 0.111578 0.111390 0.112358 
        ///0.135294 0.098703 0.110545 0.122943 0.103426 
        ///0.138587 0.112021 0.106155 0.112148 0.098333 
        ///0.139337 0.099085 0.128768 0.086019 0.119196 
        ///0.142718 0.107216 0.091169 0.100019 0.130495 
        ///0.147706 0.094195 0.097858 0.119205 0.130316 
        ///0.139253 0.074437 0.096559 0.143926 0.138419 
        ///0.122840 0.072204 0.104933 0.144430 0.137007 
        ///0.155716 0.066609 0.080096 0.141259 0.155540 
        ///0.145838 0.072093 0.074263 0.165025 0.139426 
        ///0.143219 0.079960 0.075777 0.175177 0.118965 
        ///0.1217 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deltas2 {
            get {
                return ResourceManager.GetString("Deltas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.123999 0.124560 0.123048 0.124449 0.123805 
        ///0.138807 0.139454 0.128684 0.137688 0.083931 
        ///0.121202 0.140247 0.113702 0.159550 0.092368 
        ///0.109026 0.131601 0.132036 0.169451 0.084580 
        ///0.096191 0.136553 0.127900 0.200053 0.066133 
        ///0.093298 0.143214 0.127912 0.194168 0.069019 
        ///0.100673 0.124589 0.141578 0.170118 0.071227 
        ///0.091974 0.132170 0.135522 0.187170 0.070364 
        ///0.091570 0.131484 0.127552 0.179209 0.078200 
        ///0.077261 0.136752 0.119413 0.197279 0.081446 
        ///0.090816 0.130584 0.106919 0.211269 0.070789 
        ///0.1083 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Deltas3 {
            get {
                return ResourceManager.GetString("Deltas3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.000000 100.000000 100.000000 100.000000 100.000000 
        ///97.971588 99.059206 102.269219 102.545536 98.124214 
        ///96.274922 96.117635 101.274791 101.927842 96.923634 
        ///97.394924 95.731815 103.172259 101.899384 99.836771 
        ///95.661483 96.863988 105.896536 104.158328 99.661501 
        ///95.091692 95.223413 103.829025 103.884486 102.767859 
        ///97.234947 95.996418 105.234639 105.592241 103.433666 
        ///95.747680 95.303107 106.555877 107.200109 102.189493 
        ///97.313333 97.679813 105.377733 109.318207 101.467331 
        ///95.542629 97.416515 107.1171 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Market1 {
            get {
                return ResourceManager.GetString("Market1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.000000 100.000000 100.000000 100.000000 100.000000 
        ///97.299172 105.986478 103.124608 100.221702 105.042858 
        ///95.356552 101.061236 102.624213 101.086022 104.798361 
        ///95.669927 104.707219 97.573762 108.423598 99.715996 
        ///94.798315 102.566101 107.020736 104.516074 97.464093 
        ///99.397688 112.034191 111.351757 105.498959 102.809215 
        ///99.894634 117.661291 110.298357 99.173912 100.269624 
        ///101.007856 114.426479 105.001120 96.319307 97.928394 
        ///97.112642 120.143106 115.618284 99.651983 97.136889 
        ///97.564909 116.472858 11 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Market2 {
            get {
                return ResourceManager.GetString("Market2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.000000 100.000000 100.000000 100.000000 100.000000 
        ///97.089662 97.019432 98.038052 97.147032 102.918994 
        ///98.952196 97.108527 99.664839 95.368222 102.067250 
        ///100.346667 98.087819 97.974141 94.672526 103.178648 
        ///103.289847 99.145391 99.838753 93.555565 107.667788 
        ///103.257914 98.169594 99.553065 93.779357 106.660029 
        ///105.283886 102.591911 100.806797 98.090858 109.442298 
        ///104.470229 100.166341 99.805170 95.220055 107.589448 
        ///105.821972 101.295372 101.674179 96.770643 107.671768 
        ///107.062380 100.209988 102.019 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Market3 {
            get {
                return ResourceManager.GetString("Market3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94.355264
        ///94.347879
        ///93.665565
        ///94.259409
        ///94.542535
        ///94.449688
        ///95.174574
        ///95.012400
        ///95.600177
        ///95.534224
        ///95.433425
        ///95.427137
        ///95.489258
        ///96.216913
        ///96.857378
        ///97.016301
        ///96.890699
        ///96.642770
        ///96.901613
        ///97.322562
        ///96.636384
        ///96.995238
        ///96.774356
        ///97.412403
        ///97.802697
        ///97.522854
        ///97.538057
        ///97.230873
        ///97.207220
        ///97.372396
        ///97.350714
        ///97.734727
        ///97.685902
        ///97.351115
        ///97.072048
        ///97.164121
        ///97.061206
        ///97.092206
        ///96.752262
        ///96.901230
        ///96.853846
        ///96.798995
        ///96.757213
        ///96.731446
        ///96.800667
        ///96.802416
        ///96.966518
        ///97.116359
        ///97.495217
        ///97.645217
        ///97.915667
        ///97 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prix1 {
            get {
                return ResourceManager.GetString("Prix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 93.308296
        ///94.608080
        ///94.069050
        ///94.170465
        ///94.379157
        ///97.282347
        ///96.705841
        ///95.493694
        ///96.720352
        ///96.051293
        ///96.254377
        ///97.898257
        ///97.981432
        ///97.271451
        ///96.542569
        ///95.530035
        ///95.821342
        ///96.294315
        ///95.074085
        ///95.152329
        ///94.304726
        ///95.544245
        ///95.696850
        ///95.112580
        ///94.894111
        ///96.006517
        ///96.069707
        ///96.450016
        ///97.248172
        ///97.492087
        ///97.451265
        ///96.408870
        ///96.521360
        ///96.995253
        ///96.205825
        ///95.888019
        ///95.963718
        ///95.657957
        ///95.087882
        ///94.985208
        ///95.075505
        ///94.935011
        ///94.915334
        ///95.555711
        ///95.398963
        ///95.196752
        ///95.351739
        ///95.416709
        ///97.002544
        ///97.422708
        ///97.838273
        ///97 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prix2 {
            get {
                return ResourceManager.GetString("Prix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97.713314
        ///96.705335
        ///96.916877
        ///96.965079
        ///97.729565
        ///97.605357
        ///99.537539
        ///98.411242
        ///99.262102
        ///98.832546
        ///99.753547
        ///99.114025
        ///97.261073
        ///96.860335
        ///96.333217
        ///95.789251
        ///95.710636
        ///95.861899
        ///95.053031
        ///95.294820
        ///96.324463
        ///95.745453
        ///97.206117
        ///96.970301
        ///97.211726
        ///96.289394
        ///96.363116
        ///96.699552
        ///97.518664
        ///97.686287
        ///97.689861
        ///98.252243
        ///97.813110
        ///97.822843
        ///97.634761
        ///98.512928
        ///97.450941
        ///97.076366
        ///97.097921
        ///96.965513
        ///97.279840
        ///98.363076
        ///96.997370
        ///96.775874
        ///96.221938
        ///96.080359
        ///95.699901
        ///95.273320
        ///94.458768
        ///93.675026
        ///94.016112
        ///94 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prix3 {
            get {
                return ResourceManager.GetString("Prix3", resourceCulture);
            }
        }
    }
}
